appName: "onix-local"
log:
  level: debug
  destinations:
    - type: stdout
  contextKeys:
    - transaction_id
    - message_id
    - subscriber_id
    - module_id
http:
  port: 8082
  timeout:
    read: 30
    write: 30
    idle: 30
pluginManager:
  root: ./plugins
plugins:
  otelsetup:
    id: otelsetup
    config:
      serviceName: "beckn-onix"
      otlpEndpoint: "otel-collector-bpp:4317"
      enableMetrics: "true"
      enableTracing: "true"
      enableLogs: "true"
      timeInterval: "5"
      auditFieldsConfig: "/app/config/audit-fields.yaml" # this can be git url
      producer: 'greedy-pony-bubbling.ngrok-free.dev'
      producerType: "bpp"
modules:
  - name: bppTxnReceiver
    path: /bpp/receiver/
    handler:
      type: std
      role: bpp
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: https://fabric.nfh.global/registry/dedi
            registryName: subscribers.beckn.one
            timeout: 10
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: 'greedy-pony-bubbling.ngrok-free.dev'
            keyId: '76EU7hRSVYMcJANsMMrhFPHKd5CEJNzAWpz4hVC7FQhKqnm6VyMpRb'
            signingPrivateKey: 'aMHqwCRjww9u4TFD0CTT+gSNg3V4Ehw/ECwfZIgyEEg='
            signingPublicKey: 'ByLFEBucCC4bWAS9bEJAiEfDKw6QqI0HesI7SAALPN8='
            encrPrivateKey: 'aMHqwCRjww9u4TFD0CTT+gSNg3V4Ehw/ECwfZIgyEEg='
            encrPublicKey: 'ByLFEBucCC4bWAS9bEJAiEfDKw6QqI0HesI7SAALPN8='
        schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-v2/refs/tags/core-v2.0.0-lts/api/v2.0.0/beckn.yaml
            cacheTTL: "3600"
            extendedSchema_enabled: "false"
            extendedSchema_cacheTTL: "86400"
            extendedSchema_maxCacheSize: "100"
            extendedSchema_downloadTimeout: "30"
            extendedSchema_allowedDomains: "raw.githubusercontent.com,schema.beckn.io,schema.ion.id"
        cache:
          id: cache
          config:
            addr: redis:6379
        signValidator:
          id: signvalidator
        router:
          id: router
          config:
            routingConfig: ./config/local-simple-routing-BPPReceiver.yaml
      steps:
        - validateSign
        - addRoute
        - validateSchema
  
  - name: bppTxnCaller
    path: /bpp/caller/
    handler:
      type: std
      role: bpp
      subscriberId: 'greedy-pony-bubbling.ngrok-free.dev'
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: https://fabric.nfh.global/registry/dedi
            registryName: subscribers.beckn.one
            timeout: 10
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: 'greedy-pony-bubbling.ngrok-free.dev'
            keyId: '76EU7hRSVYMcJANsMMrhFPHKd5CEJNzAWpz4hVC7FQhKqnm6VyMpRb'
            signingPrivateKey: 'aMHqwCRjww9u4TFD0CTT+gSNg3V4Ehw/ECwfZIgyEEg='
            signingPublicKey: 'ByLFEBucCC4bWAS9bEJAiEfDKw6QqI0HesI7SAALPN8='
            encrPrivateKey: 'aMHqwCRjww9u4TFD0CTT+gSNg3V4Ehw/ECwfZIgyEEg='
            encrPublicKey: 'ByLFEBucCC4bWAS9bEJAiEfDKw6QqI0HesI7SAALPN8='
        schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-v2/refs/tags/core-v2.0.0-lts/api/v2.0.0/beckn.yaml
            cacheTTL: "3600"
            extendedSchema_enabled: "true"
            extendedSchema_cacheTTL: "86400"
            extendedSchema_maxCacheSize: "100"
            extendedSchema_downloadTimeout: "30"
            extendedSchema_allowedDomains: "raw.githubusercontent.com,schema.beckn.io,schema.ion.id"
        cache:
          id: cache
          config:
            addr: redis:6379
        router:
          id: router
          config:
            routingConfig: ./config/local-simple-routing-BPPCaller.yaml
        signer:
          id: signer
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bpp
      steps:
        - addRoute
        - sign
        - validateSchema
