services:
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - beckn_network
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "ping" ]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5

  onix-bap:
    image: fidedocker/onix-adapter:latest
    container_name: onix-bap
    platform: linux/amd64
    networks:
      - beckn_network
    ports:
      - "8081:8081"
    environment:
      CONFIG_FILE: "/app/config/local-simple-bap.yaml"
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      REDIS_ADDR: redis:6379
      RABBITMQ_ADDR: rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector-bap:4317
    volumes:
      - ./config:/app/config
      - ./schemas:/app/schemas
    command: [ "./server", "--config=/app/config/local-simple-bap.yaml" ]

  otel-collector-bap:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-bap
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./config/otel-collector-bap/config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - beckn_network
    restart: unless-stopped

  nginx-bap:
    image: nginx:alpine
    container_name: nginx-bap
    networks:
      - beckn_network
    volumes:
      - ./config/nginx-bap.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - onix-bap
    restart: unless-stopped

  ngrok-bap:
    image: ngrok/ngrok:latest
    container_name: ngrok-bap
    profiles:
      - ngrok
    networks:
      - beckn_network
    depends_on:
      - nginx-bap
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --url=${NGROK_DOMAIN} http://nginx-bap:80
    ports:
      - "4041:4040"
    restart: unless-stopped

networks:
  beckn_network:
    name: beckn_network
    driver: bridge
